application: appendr
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

- name: webob
  version: latest


handlers:
- url: /web/stylesheets.*
  static_dir: web/stylesheets

- url: /favicon.ico
  static_files: web/favicon.ico
  upload: web/favicon.ico

- url: /tasks/append/.*
  script: appendr.app
  login: admin

- url: /tasks/cleanup_bins
  script: appendr.app
  login: admin

- url: /tasks/cleanup_taskstatus
  script: appendr.app
  login: admin

- url: /.*
  script: appendr.app
  secure: always
