application: appendr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: appendr.app
  secure: always

- url: /tasks/append/.*
  script: appendr.app
  login: admin
